# Generated by Django 4.1.5 on 2023-01-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('patientname', models.CharField(max_length=50)),
                ('doctoremail', models.EmailField(max_length=50)),
                ('patientemail', models.EmailField(max_length=50)),
                ('appoitmentdate', models.DateField()),
                ('appoitmenttime', models.TimeField()),
                ('symptoms', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('specialization', models.CharField(max_length=50)),
                ('npwz', models.CharField(max_length=10)),
            ],
        ),
    ]
