# Generated by Django 4.1.5 on 2023-01-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appoitment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoitment',
            old_name='prescription',
            new_name='exam',
        ),
    ]
